// Autogenerated from Pigeon (v3.2.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class SetLoggableRequest;
@class SupportSDKInitializeRequest;
@class ChatSDKV2InitializeRequest;
@class RegisterPushTokenRequest;
@class SetVisitorIdentityRequest;
@class VisitorTagsRequest;
@class SetVisitorCustomInfoRequest;

@interface SetLoggableRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLoggable:(NSNumber *)loggable;
@property(nonatomic, strong) NSNumber * loggable;
@end

@interface SupportSDKInitializeRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithZendeskUrl:(NSString *)zendeskUrl
    appId:(NSString *)appId
    clientId:(NSString *)clientId;
@property(nonatomic, copy) NSString * zendeskUrl;
@property(nonatomic, copy) NSString * appId;
@property(nonatomic, copy) NSString * clientId;
@end

@interface ChatSDKV2InitializeRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAccountKey:(NSString *)accountKey
    appId:(NSString *)appId;
@property(nonatomic, copy) NSString * accountKey;
@property(nonatomic, copy) NSString * appId;
@end

@interface RegisterPushTokenRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPushToken:(NSString *)pushToken;
@property(nonatomic, copy) NSString * pushToken;
@end

@interface SetVisitorIdentityRequest : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    email:(nullable NSString *)email
    phoneNumber:(nullable NSString *)phoneNumber;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * phoneNumber;
@end

@interface VisitorTagsRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTags:(NSArray<NSString *> *)tags;
@property(nonatomic, strong) NSArray<NSString *> * tags;
@end

@interface SetVisitorCustomInfoRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCustomInfo:(NSString *)customInfo;
@property(nonatomic, copy) NSString * customInfo;
@end

/// The codec used by ZendeskSDKApi.
NSObject<FlutterMessageCodec> *ZendeskSDKApiGetCodec(void);

@protocol ZendeskSDKApi
- (void)setLoggableRequest:(SetLoggableRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ZendeskSDKApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ZendeskSDKApi> *_Nullable api);

/// The codec used by SupportSDKApi.
NSObject<FlutterMessageCodec> *SupportSDKApiGetCodec(void);

@protocol SupportSDKApi
- (void)initializeSupportSDKRequest:(SupportSDKInitializeRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)showHelpCenterWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SupportSDKApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SupportSDKApi> *_Nullable api);

/// The codec used by ChatSDKV2Api.
NSObject<FlutterMessageCodec> *ChatSDKV2ApiGetCodec(void);

@protocol ChatSDKV2Api
- (void)initializeChatSDKRequest:(ChatSDKV2InitializeRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerPushTokenRequest:(RegisterPushTokenRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startChatWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChatSDKV2ApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatSDKV2Api> *_Nullable api);

/// The codec used by ProfileProviderApi.
NSObject<FlutterMessageCodec> *ProfileProviderApiGetCodec(void);

@protocol ProfileProviderApi
- (void)setVisitorIdentityRequest:(SetVisitorIdentityRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)addVisitorTagsRequest:(VisitorTagsRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeVisitorTagsRequest:(VisitorTagsRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVisitorCustomInfoRequest:(SetVisitorCustomInfoRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearVisitorInfoWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ProfileProviderApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ProfileProviderApi> *_Nullable api);

NS_ASSUME_NONNULL_END
